INSERT INTO comment (comment_text, user_id, post_id)
VALUES
    ('SUPPPPPER GOOD POST', 1, 1)
    ('SUPPPPPER GOOOD POST', 1, 2)
    ('SUPPPPPER GOOOOD POST', 2, 1)
    ('SUPPPPPER GOOOOOD POST', 2, 2)
    ('SUPPPPPER GOOOOOOD POST', 3, 1)
    ('SUPPPPPER GOOOOOOOD POST', 3, 2)
    ('SUPPPPPER GOOOOOOOOOD POST', 4, 1)
    ('SUPPPPPER GOOOOOOOOOOD POST', 4, 2)
    ('SUPPPPPER GOOOOOOOOOOOD POST', 5, 1)
    ('SUPPPPPER GOOOOOOOOOOOOD POST', 5, 2);